version: 2.1
orbs:
  maven: circleci/maven@2.1.0 # Use the latest version

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - maven/with-cache:
          steps:
            - run: mvn clean install
      - store_test_results:
          path: target/
workflows:
  build-workflow:
    jobs:
      - build-and-test